<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX59BVxB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX59BVxB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX59BVxB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX59BVxB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX59BVxB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X59BVxB',
    'container.build_id' => 'b36d30de',
    'container.build_time' => 1559660580,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX59BVxB');
