<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbULPFl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbULPFl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXbULPFl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXbULPFl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXbULPFl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XbULPFl',
    'container.build_id' => '356dfe01',
    'container.build_time' => 1559739415,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbULPFl');
