<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'switch_language' => [['_locale', 'locale'], ['_controller' => 'App\\Controller\\Front\\LocaleSwitchController::switchLanguage', '_locale' => 'fr'], ['_locale' => 'en|fr'], [['variable', '/', '[^/]++', 'locale'], ['text', '/switch'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'homepage.fr' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::index', '_locale' => 'fr', '_canonical_route' => 'homepage'], ['_locale' => 'en|fr'], [['text', '/'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'homepage.en' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::index', '_locale' => 'fr', '_canonical_route' => 'homepage'], ['_locale' => 'en|fr'], [['text', '/home'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'projets.fr' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::projet', '_locale' => 'fr', '_canonical_route' => 'projets'], ['_locale' => 'en|fr'], [['text', '/projets'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'projets.en' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::projet', '_locale' => 'fr', '_canonical_route' => 'projets'], ['_locale' => 'en|fr'], [['text', '/projects'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'exp.fr' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::experiences', '_locale' => 'fr', '_canonical_route' => 'exp'], ['_locale' => 'en|fr'], [['text', '/experiences'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'exp.en' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::experiences', '_locale' => 'fr', '_canonical_route' => 'exp'], ['_locale' => 'en|fr'], [['text', '/experiences'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'cv.fr' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::cv', '_locale' => 'fr', '_canonical_route' => 'cv'], ['_locale' => 'en|fr'], [['text', '/cv'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'cv.en' => [['_locale'], ['_controller' => 'App\\Controller\\Front\\MainController::cv', '_locale' => 'fr', '_canonical_route' => 'cv'], ['_locale' => 'en|fr'], [['text', '/resume'], ['variable', '/', 'en|fr', '_locale']], [], []],
    'admin.index' => [[], ['_controller' => 'App\\Controller\\Back\\MainController::index'], [], [['text', '/admin/']], [], []],
    'index' => [[], ['_locale' => 'en', '_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
];
