<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.c48hWyN' shared service.

return $this->privates['.service_locator.c48hWyN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MainController::index' => ['privates', '.service_locator.IHwrv57', 'get_ServiceLocator_IHwrv57Service.php', true],
    'App\\Controller\\MainController:index' => ['privates', '.service_locator.IHwrv57', 'get_ServiceLocator_IHwrv57Service.php', true],
], [
    'App\\Controller\\MainController::index' => '?',
    'App\\Controller\\MainController:index' => '?',
]);
