<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IHwrv57' shared service.

return $this->privates['.service_locator.IHwrv57'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'defaultLocale' => ['privates', '.value.QlkNiym', 'get_Value_QlkNiymService.php', true],
    'locales' => ['privates', '.value.OkZqvkn', 'get_Value_OkZqvknService.php', true],
    'translator' => ['services', 'translator', 'getTranslatorService', false],
], [
    'defaultLocale' => '?',
    'locales' => '?',
    'translator' => '?',
]);
