<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\LocaleSwitchController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/LocaleSwitchController.php';

$this->services['App\\Controller\\LocaleSwitchController'] = $instance = new \App\Controller\LocaleSwitchController();

$instance->setContainer(($this->privates['.service_locator.h1yB4D5'] ?? $this->load('get_ServiceLocator_H1yB4D5Service.php'))->withContext('App\\Controller\\LocaleSwitchController', $this));

return $instance;
